# Generated by Django 5.2.6 on 2025-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='team_image', verbose_name='COVER'),
        ),
    ]
