# Generated by Django 5.2.6 on 2025-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
