# Generated by Django 5.2.6 on 2025-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='link',
            field=models.URLField(blank=True, verbose_name='LINK'),
        ),
    ]
