# Generated by Django 5.2.6 on 2025-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_team_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=367)),
                ('titles', models.IntegerField()),
                ('league_picture', models.ImageField(blank=True, upload_to='league_pics', verbose_name='LEAGUE')),
                ('link_to_site', models.URLField(blank=True, verbose_name='LINK')),
                ('last_five', models.CharField(max_length=5)),
            ],
        ),
    ]
