# Generated by Django 5.2.6 on 2025-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_five',
            field=models.CharField(max_length=90),
        ),
    ]
