# Generated by Django 5.2.6 on 2025-12-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_article_last_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.team'),
            preserve_default=False,
        ),
    ]
