# Generated by Django 5.2.6 on 2026-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='league_picture',
            field=models.ImageField(blank=True, upload_to='league_pics/', verbose_name='LEAGUE'),
        ),
    ]
