# Generated by Django 5.2.6 on 2026-02-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_article_league_picture'),
        ('reviews', '0003_alter_review_name_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.team'),
        ),
    ]
